name: Docker Image CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the codebase
        uses: actions/checkout@v3

      - name: Configure Aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g1b6z7n7

      - name: Build, tag and push the Docker image
        run: |
          docker build . -t roadromeo1/ci-cd-php
          docker tag roadromeo1/ci-cd-php:latest public.ecr.aws/g1b6z7n7/roadromeo1/ci-cd-php:latest
          docker push public.ecr.aws/g1b6z7n7/roadromeo1/ci-cd-php:latest
